server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: myblog

  jpa:
    hibernate:
      ddl-auto: update
#      none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    logging:
      level:
        org:
          hibernate:
            SQL: DEBUG
            type:
              descriptor: TRACE

  sql:
    init:
      mode: never
  # SpringBoot 시작시 sql 고유 스크립트 수행 옵션
  #    ALWAYS,
  #    EMBEDDED,
  #    NEVER;

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myblogbyjpa
    username: root
    password : "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver


  springdoc:
    api-docs:
      enabled: true
      path: /v3/api-docs    # 현재 swagger의 버전이 3버전이라 v3가 달렸다고함
    swagger-ui:
      enabled: true
      path: /swagger-ui/index.html    # swagger 주소 사용자 설정

